
version: '2'
services:
  mysql-standalone:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test

  exercises-mysql:
     build: .
     ports:
       - "8086:8086"
     links:
       - mysql-standalone